<a href="https://colab.research.google.com/github/brownnest/Text-analysis/blob/main/Text_analysis_w1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_excel('yelp.xlsx')

In [ ]:
df.head()

                                              review  sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [ ]:
df.shape

(1000, 2)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=500, stop_words='english')

In [ ]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
ENGLISH_STOP_WORDS

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides',
           'between',
           'beyond',
           'bill',
           'both',
           'bottom',
           'but',
           'by',
           'call',
           'can',
           'cannot',
           'cant',
           'co',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'do',
           'done',
           'down',
           'due',
           'during',
           'each',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'few',
           'fifteen',
           'fifty',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'for',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'from',
           'front',
           'full',
           'further',
           'get',
           'give',
           'go',
           'had',
           'has',
           'hasnt',
           'have',
           'he',
           'hence',
           'her',
           'here',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'hers',
           'herself',
           'him',
           'himself',
           'his',
           'how',
           'however',
           'hundred',
           'i',
           'ie',
           'if',
           'in',
           'inc',
           'indeed',
           'interest',
           'into',
           'is',
           'it',
           'its',
           'itself',
           'keep',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'many',
           'may',
           'me',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'more',
           'moreover',
           'most',
           'mostly',
           'move',
           'much',
           'must',
           'my',
           'myself',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'no',
           'nobody',
           'none',
           'noone',
           'nor',
           'not',
           'nothing',
           'now',
           'nowhere',
           'of',
           'off',
           'often',
           'on',
           'once',
           'one',
           'only',
           'onto',
           'or',
           'other',
           'others',
           'otherwise',
           'our',
           'ours',
           'ourselves',
           'out',
           'over',
           'own',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'rather',
           're',
           'same',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'she',
           'should',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'so',
           'some',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'such',
           'system',
           'take',
           'ten',
           'than',
           'that',
           'the',
           'their',
           'them',
           'themselves',
           'then',
           'thence',
           'there',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'these',
           'they',
           'thick',
           'thin',
           'third',
           'this',
           'those',
           'though',
           'three',
           'through',
           'throughout',
           'thru',
           'thus',
           'to',
           'together',
           'too',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'under',
           'until',
           'up',
           'upon',
           'us',
           'very',
           'via',
           'was',
           'we',
           'well',
           'were',
           'what',
           'whatever',
           'when',
           'whence',
           'whenever',
           'where',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'which',
           'while',
           'whither',
           'who',
           'whoever',
           'whole',
           'whom',
           'whose',
           'why',
           'will',
           'with',
           'within',
           'without',
           'would',
           'yet',
           'you',
           'your',
           'yours',
           'yourself',
           'yourselves'})

In [ ]:
dtm = cv.fit_transform(df['review'])

In [ ]:
dtm.shape

(1000, 500)

In [ ]:
cv.get_feature_names_out()

array(['10', '20', '30', '35', '40', 'absolutely', 'actually', 'added',
       'ago', 'amazing', 'ambiance', 'ambience', 'anytime', 'area',
       'arrived', 'ask', 'asked', 'ate', 'atmosphere', 'attentive',
       'authentic', 'average', 'avoid', 'away', 'awesome', 'awful',
       'bacon', 'bad', 'bar', 'barely', 'bathroom', 'bay', 'beans',
       'beat', 'beautiful', 'beef', 'beer', 'believe', 'best', 'better',
       'big', 'bit', 'bland', 'boyfriend', 'bread', 'breakfast', 'bring',
       'brought', 'brunch', 'buffet', 'burger', 'burgers', 'business',
       'busy', 'butter', 'cafe', 'came', 'care', 'check', 'checked',
       'cheese', 'chef', 'chewy', 'chicken', 'chips', 'clean', 'close',
       'cold', 'come', 'coming', 'considering', 'cooked', 'cool',
       'couldn', 'couple', 'course', 'cow', 'crab', 'crazy', 'cream',
       'creamy', 'crispy', 'crowd', 'crust', 'curry', 'customer',
       'customers', 'cut', 'cute', 'damn', 'dark', 'day', 'deal',
       'dealing', 'decent', 'decided', 'decor', 'decorated', 'definately',
       'definitely', 'delicious', 'delight', 'delightful', 'delish',
       'deserves', 'dessert', 'desserts', 'did', 'didn', 'die',
       'different', 'dine', 'dining', 'dinner', 'dirt', 'dirty',
       'disappoint', 'disappointed', 'disappointing', 'disappointment',
       'disgusting', 'dish', 'dishes', 'disrespected', 'does', 'dog',
       'don', 'dont', 'door', 'double', 'doubt', 'downtown', 'dressing',
       'driest', 'drink', 'drinks', 'drive', 'dry', 'duck', 'eat',
       'eaten', 'eating', 'edible', 'egg', 'enjoy', 'enjoyed', 'equally',
       'especially', 'establishment', 'excellent', 'expect', 'expected',
       'experience', 'extremely', 'fact', 'family', 'fantastic', 'far',
       'fast', 'favorite', 'feel', 'felt', 'fine', 'fish', 'flat',
       'flavor', 'flavorful', 'folks', 'food', 'fresh', 'fried', 'friend',
       'friendly', 'friends', 'fries', 'frozen', 'fun', 'gave',
       'generous', 'getting', 'going', 'gone', 'good', 'got', 'grease',
       'great', 'greek', 'green', 'greeted', 'grill', 'grilled', 'gross',
       'guess', 'guy', 'gyros', 'hair', 'half', 'hands', 'happy', 'hard',
       'healthy', 'heart', 'helpful', 'high', 'highly', 'hit', 'home',
       'homemade', 'honest', 'hope', 'horrible', 'hot', 'hour', 'house',
       'huge', 'hummus', 'husband', 'ice', 'immediately', 'impressed',
       'incredible', 'inside', 'insulted', 'interesting', 'isn', 'job',
       'just', 'kept', 'kind', 'know', 'lacked', 'lacking', 'large',
       'leave', 'left', 'let', 'like', 'liked', 'list', 'literally',
       'little', 'live', 'll', 'lobster', 'location', 'long', 'look',
       'lot', 'love', 'loved', 'lunch', 'make', 'management', 'manager',
       'maybe', 'meal', 'meals', 'meat', 'mediocre', 'melt', 'menu',
       'min', 'mind', 'minutes', 'moist', 'mom', 'money', 'mouth',
       'multiple', 'music', 'nachos', 'nasty', 'need', 'needed',
       'needless', 'needs', 'neighborhood', 'new', 'nice', 'nicest',
       'night', 'non', 'note', 'offers', 'oh', 'ok', 'old', 'omg',
       'opportunity', 'options', 'order', 'ordered', 'orders', 'outside',
       'outstanding', 'oven', 'overall', 'overcooked', 'overpriced',
       'overwhelmed', 'owner', 'owners', 'pace', 'paid', 'pancakes',
       'paper', 'par', 'party', 'passed', 'pasta', 'patio', 'pay',
       'people', 'pepper', 'perfect', 'perfection', 'perfectly', 'person',
       'pho', 'phoenix', 'piece', 'pita', 'pizza', 'pizzas', 'place',
       'places', 'plate', 'playing', 'pleasant', 'pleased', 'plus',
       'point', 'poor', 'pop', 'pork', 'portion', 'portions', 'possible',
       'potato', 'potatoes', 'preparing', 'presentation', 'pretty',
       'price', 'priced', 'prices', 'pricing', 'probably', 'pulled',
       'quality', 'quick', 'quickly', 'quite', 'rare', 'real', 'really',
       'reasonable', 'received', 'recommend', 'recommendation',
       'recommended', 'regular', 'restaurant', 'restaurants', 'return',
       'review', 'reviews', 'rice', 'right', 'rolls', 'room', 'rude',
       'running', 'sad', 'said', 'salad', 'salmon', 'salsa', 'salt',
       'sandwich', 'sashimi', 'sat', 'sauce', 'say', 'seafood', 'seated',
       'seating', 'second', 'selection', 'seriously', 'served', 'server',
       'servers', 'service', 'setting', 'shrimp', 'sick', 'sides', 'slow',
       'small', 'soggy', 'soon', 'soup', 'special', 'spicy', 'spot',
       'staff', 'stale', 'star', 'stars', 'stay', 'steak', 'steaks',
       'stomach', 'stop', 'strip', 'style', 'subway', 'sucked', 'sucks',
       'super', 'sure', 'sushi', 'sweet', 'table', 'tables', 'tacos',
       'talk', 'taste', 'tasted', 'tasteless', 'tasty', 'tea', 'tell',
       'tender', 'terrible', 'texture', 'thai', 'thing', 'things',
       'think', 'thought', 'thumbs', 'time', 'times', 'tip', 'today',
       'told', 'took', 'total', 'totally', 'town', 'treated', 'tried',
       'trip', 'try', 'twice', 'unfortunately', 'unless', 'used', 've',
       'vegas', 'vegetables', 'vegetarian', 'vibe', 'visit', 'wait',
       'waited', 'waiter', 'waiting', 'waitress', 'walked', 'wall',
       'want', 'wanted', 'warm', 'wasn', 'waste', 'watched', 'water',
       'way', 'went', 'white', 'wife', 'wine', 'wings', 'won',
       'wonderful', 'word', 'work', 'world', 'worse', 'worst', 'worth',
       'wouldn', 'wow', 'wrong', 'years', 'yummy', 'zero'], dtype=object)

In [ ]:
dtm.sum(axis=0)

matrix([[  5,   4,   5,   3,   4,   8,   2,   2,   3,  24,   7,   3,   5,
           7,   3,   4,   5,   3,  11,   7,   6,   4,   5,   5,  12,   3,
           5,  18,   7,   5,   3,   4,   3,   4,   3,   5,   8,   3,  30,
          16,   3,   8,  11,   3,   5,  10,   5,   3,   3,  11,  12,   4,
           4,   3,   3,   3,  20,   3,   7,   3,   3,   4,   3,  17,   7,
           9,   4,   9,  11,  10,   4,   7,   3,   3,   3,   3,   2,   2,
           2,   4,   2,   2,   2,   2,   2,   6,   2,   2,   2,   4,   2,
           9,   7,   2,   2,   2,   3,   2,   2,  19,  23,   2,   2,   3,
           3,   5,   3,  22,  13,   2,   3,   2,   8,   6,   2,   4,   2,
          19,   5,   4,   2,   8,   9,   2,   2,   3,  26,   2,   3,   2,
           2,   2,   3,   2,   4,   4,   4,   4,   3,  19,   5,   8,   3,
           3,   6,   5,   3,   3,   4,  10,   5,   3,  20,   5,   4,   7,
          12,   7,   5,   3,  11,   8,   3,   5,   3,  13,   3,   4, 126,
          14,   5,   5,  27,   4,   9,   3,   4,   4,   3,   8,  18,   3,
          95,  18,   2,  70,   3,   3,   2,   2,   2,   2,   3,   2,   2,
           2,   3,   3,   8,   6,   3,   4,   4,   4,   4,   5,   5,   3,
           3,   3,   6,   9,   6,   4,   5,   3,   4,   5,   3,   8,   4,
           7,   3,   3,   3,   4,  35,   5,   4,  11,   3,   3,   4,   4,
           6,   3,  46,   3,   3,   3,  10,   4,  13,   3,   4,   5,   4,
           7,  19,  10,  10,   8,   6,   4,   3,  11,   3,   9,   6,   3,
          15,   2,   2,  19,   3,   3,   6,   3,   2,   3,   2,   3,   3,
           2,   2,   4,   2,   5,  25,   2,  12,   2,   2,   2,   3,   3,
           5,   2,   2,   4,  11,  14,   2,   5,   3,   2,   8,   2,   7,
           2,   4,   4,   2,   2,   2,   2,   3,   3,   2,   5,   3,   4,
           9,   2,  10,   2,   3,   2,   6,   4,   4,   3,  15,   3, 106,
           5,   2,   2,   3,   3,   2,   3,   6,   2,   4,   2,   5,   4,
           6,   3,   2,   2,  20,   7,   3,  10,   2,  10,   3,  14,   5,
           3,   8,   4,   5,  36,   5,   3,  11,   3,   3,   3,  25,   3,
           5,   3,   3,   4,   9,   3,   3,   8,   4,   4,   8,  15,   4,
           3,   3,   9,   3,   5,  10,  16,   5,   5,   3,   3,  10,   7,
           6,  13,   5,  85,   3,   6,   5,   3,  11,   6,   3,   9,   4,
           7,   8,   8,  19,   3,   3,  15,   3,  14,   4,   3,   3,   3,
           3,   3,   4,   3,   7,   8,  13,   5,   9,   5,   4,   5,  13,
           8,   5,  11,   4,   6,   6,  10,   3,   5,   8,   5,  16,   5,
           4,  42,  13,   3,   4,   3,   8,   3,   3,   7,   3,   7,   4,
           8,   6,   4,   3,   3,  23,  22,   4,   3,   3,   4,  14,  10,
           7,   5,   8,   3,   3,  13,   3,   7,  13,   5,   3,   3,  15,
          13,   3,   3,   4,   4,  19,   7,   2,   2,   3,   3,  15,  10,
           3,   3,   5,   3,   4,   5]])

In [ ]:
dtm.sum(axis=1)

matrix([[ 3],
        [ 2],
        [ 4],
        [ 2],
        [ 4],
        [ 4],
        [ 3],
        [ 5],
        [ 2],
        [ 1],
        [ 1],
        [ 0],
        [ 3],
        [ 2],
        [ 3],
        [ 0],
        [ 2],
        [ 4],
        [ 5],
        [ 2],
        [ 0],
        [ 2],
        [ 2],
        [ 3],
        [ 0],
        [ 2],
        [ 3],
        [ 5],
        [11],
        [ 3],
        [ 6],
        [ 1],
        [ 1],
        [ 6],
        [ 4],
        [ 2],
        [ 3],
        [ 8],
        [ 2],
        [ 2],
        [ 3],
        [ 3],
        [ 8],
        [ 5],
        [ 3],
        [ 4],
        [ 3],
        [ 6],
        [ 3],
        [ 7],
        [ 7],
        [ 5],
        [ 1],
        [ 7],
        [ 2],
        [ 7],
        [ 7],
        [ 3],
        [ 6],
        [ 1],
        [ 4],
        [ 2],
        [ 1],
        [ 1],
        [ 1],
        [ 5],
        [ 2],
        [ 5],
        [ 5],
        [ 3],
        [ 4],
        [ 5],
        [ 1],
        [ 3],
        [ 4],
        [ 2],
        [ 4],
        [ 4],
        [ 8],
        [ 8],
        [ 5],
        [ 6],
        [ 2],
        [ 1],
        [ 3],
        [ 6],
        [ 3],
        [ 3],
        [ 1],
        [ 2],
        [ 3],
        [ 6],
        [ 1],
        [ 3],
        [ 2],
        [ 1],
        [ 0],
        [ 3],
        [ 1],
        [ 4],
        [ 5],
        [ 6],
        [ 5],
        [ 8],
        [ 1],
        [ 2],
        [ 6],
        [ 4],
        [ 1],
        [ 1],
        [ 5],
        [ 4],
        [ 7],
        [ 3],
        [ 2],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 6],
        [ 8],
        [ 2],
        [ 4],
        [10],
        [ 9],
        [ 3],
        [ 9],
        [ 3],
        [ 2],
        [ 7],
        [ 5],
        [ 1],
        [10],
        [ 2],
        [ 5],
        [ 6],
        [ 2],
        [ 3],
        [ 7],
        [ 4],
        [ 1],
        [ 5],
        [ 6],
        [ 3],
        [ 4],
        [ 3],
        [ 7],
        [11],
        [ 1],
        [ 5],
        [ 6],
        [ 3],
        [ 2],
        [ 3],
        [ 2],
        [ 3],
        [ 6],
        [ 9],
        [ 2],
        [ 5],
        [ 3],
        [ 2],
        [ 2],
        [ 1],
        [ 2],
        [ 1],
        [ 7],
        [ 3],
        [ 3],
        [ 1],
        [ 7],
        [ 7],
        [ 1],
        [ 2],
        [ 3],
        [ 2],
        [ 2],
        [ 1],
        [ 3],
        [ 5],
        [ 9],
        [ 4],
        [ 1],
        [ 2],
        [ 7],
        [ 3],
        [ 4],
        [ 2],
        [ 2],
        [ 9],
        [ 3],
        [ 3],
        [ 3],
        [ 7],
        [ 6],
        [ 4],
        [ 3],
        [ 4],
        [ 2],
        [ 2],
        [ 4],
        [ 2],
        [ 3],
        [ 3],
        [ 2],
        [ 3],
        [ 4],
        [ 2],
        [ 2],
        [ 3],
        [ 2],
        [ 8],
        [ 3],
        [ 1],
        [ 2],
        [ 2],
        [ 2],
        [ 1],
        [ 3],
        [ 2],
        [ 5],
        [ 3],
        [ 6],
        [ 3],
        [ 4],
        [ 2],
        [ 0],
        [ 4],
        [ 0],
        [ 3],
        [ 5],
        [ 8],
        [ 2],
        [ 4],
        [ 4],
        [ 3],
        [ 7],
        [ 5],
        [ 2],
        [ 4],
        [ 5],
        [ 2],
        [ 2],
        [ 3],
        [ 6],
        [ 7],
        [ 3],
        [ 5],
        [ 2],
        [ 6],
        [ 4],
        [ 1],
        [ 4],
        [ 5],
        [ 4],
        [ 4],
        [ 2],
        [ 4],
        [ 2],
        [ 1],
        [ 2],
        [ 2],
        [ 2],
        [ 3],
        [ 4],
        [ 1],
        [ 2],
        [ 6],
        [ 3],
        [ 2],
        [ 1],
        [ 2],
        [ 1],
        [ 4],
        [ 4],
        [ 4],
        [ 4],
        [ 4],
        [ 1],
        [ 4],
        [ 5],
        [ 1],
        [ 2],
        [ 5],
        [ 4],
        [ 2],
        [ 3],
        [ 6],
        [ 2],
        [ 3],
        [ 5],
        [ 4],
        [ 7],
        [ 5],
        [ 5],
        [ 3],
        [ 7],
        [ 4],
        [ 2],
        [ 4],
        [ 7],
        [ 4],
        [ 6],
        [ 2],
        [ 3],
        [ 0],
        [ 0],
        [ 4],
        [ 3],
        [ 3],
        [ 2],
        [ 2],
        [ 2],
        [ 1],
        [ 6],
        [ 1],
        [ 5],
        [ 5],
        [ 6],
        [ 2],
        [ 1],
        [ 5],
        [ 4],
        [ 3],
        [ 3],
        [ 2],
        [ 2],
        [ 6],
        [ 7],
        [ 7],
        [ 5],
        [ 2],
        [ 4],
        [ 1],
        [ 2],
        [ 3],
        [ 3],
        [ 5],
        [ 2],
        [ 2],
        [ 1],
        [ 4],
        [ 6],
        [ 1],
        [ 5],
        [ 4],
        [ 3],
        [ 6],
        [ 3],
        [ 6],
        [ 4],
        [ 1],
        [ 3],
        [ 3],
        [ 1],
        [ 4],
        [ 5],
        [ 3],
        [ 3],
        [ 4],
        [ 4],
        [ 6],
        [ 3],
        [ 4],
        [ 6],
        [ 4],
        [ 3],
        [ 3],
        [ 4],
        [ 2],
        [ 5],
        [ 0],
        [ 2],
        [ 5],
        [ 4],
        [ 4],
        [ 3],
        [ 4],
        [ 2],
        [ 8],
        [ 1],
        [ 1],
        [ 3],
        [ 2],
        [ 2],
        [ 3],
        [ 3],
        [ 4],
        [ 0],
        [ 2],
        [ 6],
        [ 7],
        [ 3],
        [ 6],
        [ 8],
        [ 4],
        [ 3],
        [ 5],
        [ 5],
        [ 3],
        [ 1],
        [ 4],
        [ 3],
        [ 8],
        [ 7],
        [ 1],
        [ 3],
        [ 5],
        [ 2],
        [ 3],
        [ 5],
        [ 3],
        [ 2],
        [ 2],
        [ 5],
        [ 3],
        [ 0],
        [ 3],
        [ 5],
        [ 6],
        [ 6],
        [ 4],
        [ 0],
        [ 7],
        [ 0],
        [ 0],
        [ 3],
        [ 1],
        [ 0],
        [ 5],
        [ 1],
        [ 1],
        [ 3],
        [ 7],
        [ 1],
        [ 3],
        [ 2],
        [ 4],
        [ 3],
        [ 1],
        [ 3],
        [ 1],
        [ 4],
        [ 1],
        [ 4],
        [ 2],
        [ 0],
        [ 2],
        [ 7],
        [ 5],
        [ 6],
        [ 1],
        [10],
        [ 1],
        [ 3],
        [ 6],
        [ 5],
        [ 2],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 3],
        [ 2],
        [ 5],
        [ 4],
        [ 7],
        [ 9],
        [ 1],
        [ 4],
        [ 1],
        [ 1],
        [ 3],
        [ 3],
        [ 2],
        [ 4],
        [ 3],
        [ 3],
        [ 1],
        [ 1],
        [ 5],
        [ 4],
        [ 8],
        [ 3],
        [ 2],
        [ 7],
        [ 2],
        [ 4],
        [ 1],
        [ 1],
        [ 2],
        [ 2],
        [ 3],
        [ 1],
        [ 1],
        [ 0],
        [ 4],
        [ 2],
        [ 5],
        [ 2],
        [ 6],
        [ 3],
        [ 4],
        [ 2],
        [ 3],
        [ 2],
        [ 3],
        [ 0],
        [ 2],
        [ 1],
        [ 5],
        [ 3],
        [ 2],
        [ 1],
        [ 2],
        [ 4],
        [ 1],
        [ 6],
        [ 1],
        [ 5],
        [ 3],
        [ 1],
        [ 1],
        [ 2],
        [ 2],
        [ 5],
        [ 1],
        [ 5],
        [ 2],
        [ 1],
        [ 2],
        [ 3],
        [ 7],
        [ 9],
        [ 2],
        [ 3],
        [ 4],
        [ 8],
        [ 1],
        [ 3],
        [ 4],
        [ 6],
        [ 3],
        [ 3],
        [ 4],
        [ 4],
        [ 6],
        [ 1],
        [ 2],
        [ 9],
        [ 5],
        [ 2],
        [ 2],
        [ 4],
        [ 3],
        [ 3],
        [ 2],
        [ 3],
        [ 2],
        [ 2],
        [ 2],
        [ 2],
        [ 2],
        [ 6],
        [ 4],
        [ 3],
        [ 3],
        [ 2],
        [ 2],
        [ 0],
        [ 2],
        [ 3],
        [ 3],
        [ 4],
        [ 5],
        [ 7],
        [ 2],
        [ 3],
        [ 2],
        [ 5],
        [ 1],
        [ 0],
        [ 4],
        [ 2],
        [ 3],
        [ 7],
        [ 1],
        [ 2],
        [ 4],
        [ 2],
        [ 3],
        [ 4],
        [ 7],
        [ 3],
        [ 2],
        [ 3],
        [ 5],
        [ 4],
        [ 6],
        [ 2],
        [ 0],
        [12],
        [ 3],
        [ 5],
        [ 3],
        [ 2],
        [ 1],
        [ 3],
        [ 4],
        [ 1],
        [ 6],
        [ 6],
        [ 6],
        [ 4],
        [ 1],
        [ 3],
        [ 3],
        [ 4],
        [ 5],
        [ 1],
        [ 4],
        [ 1],
        [ 3],
        [10],
        [ 3],
        [ 2],
        [ 7],
        [ 3],
        [ 8],
        [ 8],
        [ 6],
        [ 5],
        [ 1],
        [ 5],
        [ 5],
        [ 2],
        [ 2],
        [ 8],
        [ 3],
        [ 1],
        [ 1],
        [ 1],
        [ 3],
        [ 3],
        [ 2],
        [ 2],
        [ 0],
        [ 3],
        [ 2],
        [ 4],
        [ 5],
        [ 5],
        [ 4],
        [ 1],
        [ 2],
        [ 3],
        [ 3],
        [ 4],
        [ 3],
        [ 3],
        [ 4],
        [ 0],
        [ 4],
        [ 1],
        [ 1],
        [ 5],
        [ 2],
        [ 5],
        [ 7],
        [ 2],
        [ 1],
        [ 2],
        [ 3],
        [ 2],
        [ 3],
        [ 2],
        [ 1],
        [ 3],
        [ 4],
        [ 3],
        [ 3],
        [ 2],
        [ 2],
        [ 4],
        [ 3],
        [ 2],
        [ 5],
        [ 4],
        [ 5],
        [ 4],
        [ 2],
        [ 3],
        [ 1],
        [ 6],
        [ 5],
        [ 4],
        [ 7],
        [ 0],
        [ 2],
        [ 5],
        [ 4],
        [ 5],
        [ 3],
        [ 4],
        [ 3],
        [ 1],
        [ 2],
        [ 1],
        [ 6],
        [ 4],
        [ 3],
        [ 1],
        [ 1],
        [ 1],
        [ 4],
        [13],
        [ 3],
        [ 2],
        [ 0],
        [ 7],
        [ 2],
        [ 6],
        [ 3],
        [ 4],
        [ 3],
        [ 4],
        [ 7],
        [ 0],
        [ 2],
        [ 3],
        [ 5],
        [ 4],
        [ 3],
        [ 4],
        [ 5],
        [ 4],
        [ 4],
        [ 6],
        [ 4],
        [ 0],
        [ 5],
        [ 2],
        [ 5],
        [ 4],
        [ 0],
        [ 5],
        [ 3],
        [ 5],
        [ 4],
        [ 5],
        [ 4],
        [ 3],
        [ 4],
        [ 5],
        [ 5],
        [ 5],
        [ 4],
        [ 3],
        [ 2],
        [ 3],
        [ 6],
        [ 5],
        [ 5],
        [ 2],
        [ 1],
        [ 3],
        [ 3],
        [ 1],
        [ 6],
        [ 4],
        [ 5],
        [ 5],
        [ 5],
        [ 3],
        [ 2],
        [ 3],
        [ 3],
        [ 3],
        [ 1],
        [ 2],
        [ 2],
        [ 2],
        [ 4],
        [ 5],
        [ 2],
        [ 1],
        [ 1],
        [ 5],
        [ 7],
        [ 5],
        [ 7],
        [ 1],
        [ 8],
        [ 2],
        [ 5],
        [ 7],
        [ 6],
        [ 2],
        [ 2],
        [ 4],
        [ 1],
        [ 3],
        [ 4],
        [ 2],
        [ 2],
        [10],
        [ 2],
        [ 6],
        [ 3],
        [ 8],
        [ 4],
        [ 2],
        [ 4],
        [ 0],
        [ 2],
        [ 3],
        [ 2],
        [ 2],
        [ 4],
        [ 1],
        [ 2],
        [ 2],
        [ 5],
        [ 1],
        [ 2],
        [ 1],
        [ 3],
        [ 4],
        [ 2],
        [ 3],
        [ 3],
        [ 2],
        [ 6],
        [ 7],
        [ 1],
        [ 8],
        [ 4],
        [ 4],
        [ 5],
        [ 1],
        [ 5],
        [ 4],
        [ 7],
        [ 1],
        [ 2],
        [ 3],
        [ 2],
        [ 5],
        [ 3],
        [ 9],
        [ 2],
        [ 1],
        [ 3],
        [ 4],
        [ 8],
        [ 3],
        [ 5],
        [ 8],
        [ 3],
        [ 4],
        [ 7],
        [ 5],
        [12],
        [ 3],
        [ 1],
        [ 2],
        [ 4],
        [ 3],
        [ 5],
        [ 9],
        [ 2],
        [ 3],
        [ 7],
        [ 5],
        [ 2],
        [ 1],
        [ 2],
        [ 2],
        [ 5],
        [ 5],
        [ 3],
        [ 4],
        [ 2],
        [ 8],
        [ 7],
        [ 1],
        [ 3],
        [ 5],
        [ 2],
        [ 6],
        [ 5],
        [ 1],
        [ 2],
        [ 2],
        [ 3],
        [ 6],
        [ 2],
        [ 2],
        [ 2],
        [ 3],
        [ 1],
        [ 4],
        [ 2],
        [ 2],
        [ 1],
        [ 4],
        [ 4],
        [ 2],
        [ 1],
        [ 4],
        [ 6],
        [ 1],
        [ 5],
        [ 2],
        [ 2],
        [ 5],
        [ 4],
        [ 3],
        [ 4],
        [ 3],
        [ 6],
        [ 2],
        [ 2],
        [ 1],
        [ 2],
        [ 6],
        [ 2],
        [ 4],
        [ 6],
        [ 2],
        [ 4],
        [ 7],
        [ 0],
        [ 2],
        [ 5],
        [ 3],
        [ 2],
        [ 2],
        [ 5],
        [ 5],
        [ 2],
        [ 1],
        [ 2],
        [ 1],
        [ 4],
        [ 1],
        [ 6],
        [ 1],
        [ 4],
        [ 8],
        [ 3],
        [ 8],
        [ 7],
        [ 1],
        [ 3],
        [ 2],
        [ 3],
        [ 3],
        [ 6],
        [ 4],
        [ 2],
        [ 7],
        [ 4],
        [ 5],
        [ 3],
        [ 3],
        [ 2],
        [ 0],
        [ 8],
        [ 6],
        [10],
        [ 3],
        [ 1],
        [ 3],
        [ 4],
        [ 1],
        [ 7],
        [ 2],
        [ 2],
        [ 6],
        [ 4],
        [ 3],
        [ 2],
        [ 9],
        [ 3],
        [ 5],
        [ 5],
        [ 3],
        [ 2],
        [ 2],
        [ 5],
        [ 3],
        [ 4],
        [ 3],
        [ 2],
        [ 5],
        [ 1],
        [ 2],
        [ 6],
        [ 5]])

In [ ]:
word_count = pd.DataFrame({
'단어': cv.get_feature_names_out(),
'빈도': dtm.sum(axis=0).flat
})

In [ ]:
word_count.sort_values('빈도', ascending=False).head()

          단어   빈도
168     food  126
324    place  106
182     good   95
393  service   85
185    great   70

In [ ]:
word_count.to_excel('word_count.xlsx')